name: Deploy HTML Files to AppServiceCMST385
on:
   push:
     branches:
       - main
jobs:
  build-and deploy:
    run-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - names: Deploy to azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name:  'CMST-MSweeney'
        slot-name: 'production'
        publish-profile: ${{  secrets.AppServiceCMST385  }}
        
